### ISSUE TITLE
Overlay Path Multiple Directories

### ISSUE THREAD

**Issue by xhesikaruci** [Nordix/xcluster#10]
I would like to use other overlays stored in different directories outside xcluster alongside with overlays provided in the ovl directory of xcluster.  However, if i set the $XCLUSTER_OVLPATH will overwrite the path that points to your overlays. Any work around?

**Comment by uablrek** [comment]
Multiple directories are separated by colon `:`. Example;
```
export XCLUSTER_OVLPATH=$HOME/xcluster/ovl:$HOME/my-ovls`
cd $HOME/xcluster
. ./Envsettings.k8s
```
