### ISSUE TITLE
Intermittent failed startup of xcluster with Kubernetes

### ISSUE THREAD

**Issue by Aoana** [Nordix/xcluster#11]
Hi!

I see an intermittent startup fault of the xcluster. The result being that kube-apiserver shuts down.
For me it happens roughly every other time.

### System info

**My machine**
```
[~] $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
[~] $ uname -r
4.15.0-43-generic
```

**My xcluster setup**

I am using the binary release [1.2](https://github.com/Nordix/xcluster/releases/download/v1.2/xcluster-v1.2.tar.xz) and a late commit on the master branch db52628.

~/xcluster (binary relase)
~/work/xcluster (git commit  db52628)

### Steps to  reproduce

Be reminded that it does not happen every time
```
cd $HOME/work/xcluster
export XCLUSTER_WORKSPACE=$HOME/xcluster/workspace
. ./Envsettings
. ./Envsettings.k8s
xc start
kubectl get nodes #hangs
```

### Additional info

The kube-apiserver seems to have shutdown:

```
vm-001 ~ # ps w | grep kube-api
 1861 root      8776 S    grep kube-api
```

The logs for the kube-apiserver is available here: [kube-apiserver.log](https://github.com/Nordix/xcluster/files/2831379/kube-apiserver.log)

**Comment by uablrek** [comment]
Without log's it's hard to guess, but I suspect `etcd`. The fresh v1.3 has a new etcd version. Please try it and check. If the problem persists, please provide logs for kube-api and etcd, they are all in `/var/log`.

**Comment by uablrek** [comment]
The "context canceled" printouts indicates some timeout I think [context](https://golang.org/pkg/context/). So it can be some general network problem. The user-space networking uses UDP multicast and is not efficient and may be disturbed by other programs and perhaps some system settings. If so, running in "netns" should work. But user-space networking works very well on Ubuntu 18 for me and I see no reason why it shouldn't work just as well on Ubuntu 16.

**Comment by Aoana** [comment]
I am running with v1.3 xcluster now, will let you know if same problems occur in the next few days. So far I have not seen the issue...

**Comment by Aoana** [comment]
Roughly two weeks have passed and I have not seen this problem since. I consider this issue solved, thanks.
