### ISSUE TITLE
Xcluster only sees one CPU

### ISSUE THREAD

**Issue by uablrek** [Nordix/xcluster#119]
Even though qemu starts with `-smp 2`, only one cpu is seen inside the vm's (/proc/cpuinfo). The console says:

```
CPU topo: Allowing 1 present CPUs plus 0 hotplug CPUs
CPU topo: Rejected CPUs 1
```
I don't know when this happened. I have tested `linux-6.10` and `linux-6.12.1`.

This may be a hint:
https://discussion.fedoraproject.org/t/fedora-sees-only-1-cpu-core-after-updating-the-kernel-from-6-8-x-to-6-9-x/121385

**Comment by uablrek** [comment]
Removing `noapic` from the kernel command-line (added by default by xcluster.sh) fixes the problem

**Comment by uablrek** [comment]
This has an impact (obviously), When using a cpu-intensive cni-plugin, like `cilium`, it made my CI-tests flaky.

**Comment by sriramy** [comment]
Should we try to apply this kernel patch? https://lore.kernel.org/all/87ttbnv75j.ffs@tglx/T/#mb379ef544bb5131f365ff5f5eb1435950bdd30a2

**Comment by uablrek** [comment]
That would probably fix the problem, but to maintain a patch is no fun in the long run. Simpler in xcluster of course, since we build the kernel, but still not fun.
I removed "noapic" in https://github.com/Nordix/xcluster/pull/120, and my CI-tests (K8s) passed just fine. Actually better, but I have made just one test-run.
If noapic is really needed in some situation, it can be added to the `$__append` variable (at the loss of all but one cpu).

Has the patch any chance of getting into the main kernel?

**Comment by sriramy** [comment]
Yes I agree, merged the PR now. Looking at the comments on the patch, looks like it will not go in as it is.

**Comment by uablrek** [comment]
Pity. Looked like a maintainer f***-up where "noapic" got mixed up with "nolapic". But I honestly can't tell.

**Comment by uablrek** [comment]
BTW the reason I noticed this was that I wanted to boost #cpu's when testing https://github.com/kubernetes/kubernetes/issues/129389. To load a service with 70000 set-entries took time :smile:

**Comment by uablrek** [comment]
@sriramy Do you know if the requirement for an apic will prevent microvm's from using >1 cpu? If so, that would be a stong motive for fixing the problem in the kernel.

**Comment by sriramy** [comment]
Sorry @uablrek on vacations now, didn't reply in time. Good to know that microvms are not affected.
