### ISSUE TITLE
xcluster network namespace ipv4-base

### ISSUE THREAD

**Issue by Aoana** [Nordix/xcluster#14]
# Background

When an xcluster namespace is created it uses addresses inside a 172.30.0.0/22 subnet for the interfaces xcluster**index** (host) host**index** (netns).
Which network that should be used can be overwritten by --ipv4-base option but it can only be set to change the first two octets. 
The only addresses that seems to be used are $__ipv4_base.0.**index** and  $__ipv4_base.1.**index**

# Problem
On my (company) network I am only allowed to use a specific /24 subnet for this purpose.
But I cannot use my subnet since xcluster requires a /22.

# Suggestion

I think the namespaces could instead just use a /24 subnet.

**Comment by uablrek** [comment]
The mask can now be specified, e.g;
```
--ipv4-base=172.30.0.128/28
```
The error checks are not fool-proof, but  basic syntax checks are made.

**Comment by Aoana** [comment]
Thanks a lot for the quick fix. I am now using this on my own /28 which is perfect!
