### ISSUE TITLE
Memory allocation __memX for vm-001 tricky to use

### ISSUE THREAD

**Issue by Aoana** [Nordix/xcluster#15]
When using xcluster with K8s the Envsettings file overwrite any memory settings you have decided on for your vm-001 and vm-201/vm-202.

**My setup**

In my profile I set to statically always allocate more memory for the base workers:
```
$ grep __mem ~/.bashrc
export __mem1=2048
export __mem2=2048
export __mem3=2048
export __mem4=2048
```
A new started terminal has the required env variables set
```
$ env | grep __mem
__mem3=2048
__mem2=2048
__mem1=2048
__mem4=2048
```
**Steps to reproduce problem**

When you source the K8s Envsettings it overwrites the value I picked for vm-001 (and would do the same for values I set for 201 and 202 as well.

```
[xcluster] $ source Envsettings.k8s
[xcluster] $ env | grep __mem
__mem=768
__mem201=384
__mem202=384
__mem3=2048
__mem2=2048
__mem1=1024
__mem4=2048
```
Some if-not-set logic would be nice in the Envsettings.K8s

**Workaround**

Set the __mem1 value after you have sourced the Envsettings file.

**Comment by uablrek** [comment]
Do not set __memX to the same value for many X. The default is __mem, set that to the most-used value and __memX for exceptions, e.g more for the k8s master and less for routers.

Updated setting;
```bash
if test -z "$__mem"; then
	export __mem=768
	export __mem1=1024
	export __mem201=384
	export __mem202=384
fi
```
