### ISSUE TITLE
Ubuntu 20.04: Network namespace creation fails, without sudo 

### ISSUE THREAD

**Issue by Aoana** [Nordix/xcluster#16]
### Problem

On my Ubuntu 20.04 laptop I am unable to create the network namespace using the xcluster scripts.
I have followed all steps in the instructions (I believe).

```
[xcluster] $ xc nsadd 1
[sudo] password for XXX:                                                   # Sudo works  
RTNETLINK answers: Operation not permitted                  # First failing here, when running command without sudo
Cannot find device "xcluster1"
Cannot find device "xcluster1"
Cannot find device "xcluster1"
Cannot find device "xcluster1"
Cannot find device "xcluster1"
Cannot find device "host1"
Cannot find device "host1"
Cannot find device "host1"
Cannot find device "host1"
Error: Nexthop has invalid gateway.
Cannot find device "host1"
Cannot find device "host1"
RTNETLINK answers: No route to host
```

### Analysis and debug

The first failure lies with creating the veth device
```
[xcluster] $ ip link add dev xcluster1 type veth peer name host1
RTNETLINK answers: Operation not permitted
```
Capabilities are set according to instructions
```
[~] $ which ip
/usr/sbin/ip
[~] $ ls -la /usr/sbin/ip
lrwxrwxrwx 1 root root 7 okt 17 09:44 /usr/sbin/ip -> /bin/ip
[~] $ getcap /bin/ip
/bin/ip = cap_net_admin,cap_sys_admin+ep
```

I cannot figure out why it fails.
This is a standard Ubuntu20.04, freshly installed.

### Additional Info

```
[~] $ uname -a
Linux ankans-dell 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
```
[~] $ sudo apt install libcap2-bin
[...]
libcap2-bin is already the newest version (1:2.32-1).
[~] $ sudo apt-get install -y iproute2
[...]
iproute2 is already the newest version (5.5.0-1ubuntu1).
```
Laptop have been restarted after setting the capabilities, with same result.  
Same problem with two different laptops both running Ubuntu 20.04.

**Comment by uablrek** [comment]
Setcap on /bin/ip does not work on Ubuntu 20. I have reported it an it is not considered an error.

Work-around; use suid bit;
```
sudo chmod a+s /bin/ip
ls -l /bin/ip 
-rwsr-sr-x 1 root root 546K Jul 15 17:16 /bin/ip
```

**Comment by Aoana** [comment]
Hi!

I have confirmed that your workaround works for me as well.
Is it possible to update the documentation to cover this case?
https://github.com/Nordix/xcluster/blob/master/doc/netns.md

In not so far future there will be a bulk of Ubuntu 20.04 users from my company (migrating from 18.04).
It would be good to reduce overhead of people needing to hit this issue.

Thanks in advance
