### ISSUE TITLE
The initial cdrom should not be unpacked on a VM reboot

### ISSUE THREAD

**Issue by uablrek** [Nordix/xcluster#53]
If a user alters a file on a VM disk that is loaded from an ovl on the initial cdrom, it will be re-initiated on a VM reboot. This is not normally what you want and may be very confusing. You want any file you modify to still be modified after a reboot.

This can be fixed `/init` (image/rootfs/init in the repo) by detecting "something" that distinguish a cold start from a reboot. For example:

```
if ! test -r /already-started; then
  touch /already-started
  # (mount cdrom etc...)
```
There might be something smarter than `/already-started`, e.g. something that already exist that indicates that the VM has been started before.

**Comment by sriramy** [comment]
Is it possible to remove the cdrom disk from qemu after first bootup? Something like a live cd during installation.

**Comment by uablrek** [comment]
Um, yeah now that you mention it, I think there is some mount-once option for cdroms. But I might have got it wrong, I just saw something like that in the man page I think...

**Comment by sriramy** [comment]
I think we should just eject the cdrom after boot. Using qmp or qemu monitor. What do you think?

**Comment by uablrek** [comment]
The qemu option I remembered  was likely "once", and is about boot, not mount. Frome "man qemu-system-x86_64":

```
                 # boot from CD-ROM first, switch back to default order after reboot
                 qemu-system-x86_64 -boot once=d
```

**Comment by sriramy** [comment]
Yeah, there doesn't seem any qemu option to detach a device after first boot. It is probably easiest to just do the simple and stupid option you mentioned, to touch a file after cdrom unpack.

I can try to investigate if we can have a shutdown script that will send a message to the monitor from inside the vm to detach cdrom. What do you think?

**Comment by uablrek** [comment]
I don't like that the VM makes kind of a signal to qemu. It doesn't feel right. But qemu _is_ a HW emulator, so it can well be that it supports a good old "eject" command to tell it to eject the cdrom.

**Comment by uablrek** [comment]
"eject" is in busybox. I'll try it, unless you beat me to it :smiley:

**Comment by uablrek** [comment]
I added "eject" in busybox, but:
```
vm-001 ~ # eject /dev/vdb
eject: /dev/vdb: Inappropriate ioctl for device
```
/dev/vdb is defined to qemu as:
```
-drive file=/path/to/cdrom.iso,if=virtio,media=cdrom
```
So, it _is_ a cdrom and should be removable. Perhaps `virtio` prevents it?

**Comment by sriramy** [comment]
From a quick look at source code, only SCSCI bus supports cdrom eject, virtio doesn't care about CDROMEJECT ioctl.

**Comment by sriramy** [comment]
Anyhow, I feel unpacking the cdrom which rewrites rootfs is the problem here. I mean, isn't it better to create rootfs outside the VM and ask qemu to boot using that rootfs?

**Comment by uablrek** [comment]
How? Using `diskim ximage ...`? If so, it seems to be something to try. But IMO, _not_ any kind of mounted fs from the host! And definitely not any NFS!!

It will add a delay on startup that might be annoying for normal clusters, but reduce startup time for large clusters or clusters with big cdroms, since unpack is done once, and not on all VMs. The unpack is however quite fast, and a reason is that the ovl tar files are uncompressed (which is intentional). A reason for creating K8s-images was actually motivated by long unpack times, but mainly for a better UE.

Actually, all bits-and-pieces are there already. Example:
```
eval $(xc env | grep XCLUSTER_)
unset XOVLS
rm -rf $XCLUSTER_TMP/disk; mkdir -p $XCLUSTER_TMP/disk
xc collect_tar --dest=$XCLUSTER_TMP/disk xnet iptools
cp -L $XCLUSTER_HOME/hd.img $XCLUSTER_TMP/disk
diskim ximage --image=$XCLUSTER_TMP/disk/hd.img $(find $XCLUSTER_TMP/disk -name '*.tar' | sort)
xc mkcdrom   # deletes any existing cdrom image
xc start --nrouters=0 --nvm=1 --image=$XCLUSTER_TMP/disk/hd.img
#xc start --nrouters=0 --nvm=1 --image=$XCLUSTER_HOME/hd.img
```
This is of course easy to make in a "mkrootfs" command in xcluster for instance.

**Comment by uablrek** [comment]
I can probably speed up `diskim` some since know more of VMs now.

**Comment by sriramy** [comment]
xc mkrootfs is what I had in mind using ximage to include all the requested ovls, and store the resulting image in $XCLUSTER_TMP, and xc start will use that image instead of the hd.img in $XCLUSTER_HOME.

**Comment by uablrek** [comment]
"xc start" already takes a "--image=" param, so no change necessary (or wanted). Unfortunately --image (and $__image) is overloaded and a tad hard to keep track of, but it's manageable. What may need updating is the test system in ovl/test. Some setting to create a rootfs instead of a cdrom (should be default for backward compatibility), an env-var or an option (which is also an env-var).

**Comment by sriramy** [comment]
Something like https://github.com/Nordix/xcluster/pull/57?
