### ISSUE TITLE
MetalLB Helm: Error: Couldn't load repositories file ($HOME/.helm/repository/repositories.yaml)

### ISSUE THREAD

**Issue by Aoana** [Nordix/xcluster#9]
### Description

I was trying to install metalllb using helm as described in the documentation:
https://github.com/Nordix/xcluster/tree/master/ovl/kubernetes#access-with-kubectl-from-your-host

When running the install I get the error that I do not have the repositories set for downloading metallb.
I am running Ubuntu 16.04LTS.

### Steps to reproduce

Following all steps described in:
https://github.com/Nordix/xcluster/tree/master/ovl/kubernetes#access-with-kubectl-from-your-host
I get the following error:

```
$ helm install --name metallb stable/metallb --debug
[debug] SERVER: "localhost:44134"
[debug] Original chart version: ""
Error: Couldn't load repositories file ($HOME/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
```
### Additional info

I am running, as instructed, tiller locally on my laptop. As described by the helm command if I run simply:
`helm init --client-only`
Then the repositories are updated in my $HOME/.helm and the helm installation works.
So my suggestion is to simply change the documentation to state:
"Do not use helm init, use helm init --client-only" or something like that.

**Comment by uablrek** [comment]
Documentation updated in v0.7
